# -*- coding: utf-8 -*-
"""3D Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vv9a3aavl6O1jsLUCjliLYp2WcjK-BN4
"""

import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

!pip install ipympl

df = pd.read_excel("S&P 500 RV.xlsx",index_col='Date',parse_dates=True, sheet_name="Returns")
df.drop(columns=["RV"], inplace=True)

df1 = pd.read_excel("RUT RV.xlsx",index_col='Date',parse_dates=True, sheet_name="Returns")
df1.drop(columns=["RV"], inplace=True)


df2 = pd.read_excel("DJIA RV.xlsx",index_col='Date',parse_dates=True, sheet_name="Returns")
df2.drop(columns=["RV"], inplace=True)

"""# 2020 Crisis

# Turbulent Period
"""

SP500=np.array(df.iloc[5044:5044+22])
RUT=np.array(df1.iloc[5044:5044+22])
DJIA=np.array(df2.iloc[5044:5044+22])

df.iloc[5044]

df.iloc[5044+22]

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib widget

from google.colab import output
output.enable_custom_widget_manager()

SP500=np.array(df.iloc[5044:5044+22])
RUT=np.array(df1.iloc[5044:5044+22])
DJIA=np.array(df2.iloc[5044:5044+22])
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(SP500, RUT, DJIA, marker='o')

ax.set_xlabel('SP500')
ax.set_ylabel('RUT')
ax.set_zlabel('DJIA')

plt.show()

"""# Preceeding Turbulent Period"""

df.iloc[5044-22:5044]

SP500=np.array(df.iloc[5044-22:5044])
RUT=np.array(df1.iloc[5044-22:5044])
DJIA=np.array(df2.iloc[5044-22:5044])
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(SP500, RUT, DJIA, marker='o')

ax.set_xlabel('SP500')
ax.set_ylabel('RUT')
ax.set_zlabel('DJIA')


plt.show()

"""# Normal Period"""

df.iloc[5044-44:5044-22]

SP500=np.array(df.iloc[5044-44:5044-22])
RUT=np.array(df1.iloc[5044-44:5044-22])
DJIA=np.array(df2.iloc[5044-44:5044-22])
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(SP500, RUT, DJIA, marker='o')

ax.set_xlabel('SP500')
ax.set_ylabel('RUT')
ax.set_zlabel('DJIA')

plt.show()

"""# 2008 Crisis

# Turbulent Period
"""

df.iloc[2167:2167+22]

SP500=np.array(df.iloc[2167:2167+22])
RUT=np.array(df1.iloc[2167:2167+22])
DJIA=np.array(df2.iloc[2167:2167+22])
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(SP500, RUT, DJIA, marker='o')

ax.set_xlabel('SP500')
ax.set_ylabel('RUT')
ax.set_zlabel('DJIA')

plt.show()

"""# Preceeding Turbulent Period"""

df.iloc[2167-22:2167]

SP500=np.array(df.iloc[2167-22:2167])
RUT=np.array(df1.iloc[2167-22:2167])
DJIA=np.array(df2.iloc[2167-22:2167])
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(SP500, RUT, DJIA, marker='o')

ax.set_xlabel('SP500')
ax.set_ylabel('RUT')
ax.set_zlabel('DJIA')


plt.show()

"""# Normal Period"""

df.iloc[2167-44:2167-22]

SP500=np.array(df.iloc[2167-44:2167-22])
RUT=np.array(df1.iloc[2167-44:2167-22])
DJIA=np.array(df2.iloc[2167-44:2167-22])
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(SP500, RUT, DJIA, marker='o')

ax.set_xlabel('SP500')
ax.set_ylabel('RUT')
ax.set_zlabel('DJIA')

plt.show()

