# -*- coding: utf-8 -*-
"""Synthetic 3D Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1caCOuaBZNq1m9D1L2q5hjyfo1C4Xb1DV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
!pip install ipympl
# %matplotlib widget
from google.colab import output
output.enable_custom_widget_manager()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

A=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])
B=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])
C=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])

Stocks=[A,B,C]

for i in range(len(Stocks)):
  for j in range(len(Stocks[i])):
    Stocks[i][j]=Stocks[i][j]+np.random.normal(0,0.05,1)

ax.scatter(Stocks[0], Stocks[1], Stocks[2], marker='o')

ax.set_xlabel('Stock A')
ax.set_ylabel('Stock B')
ax.set_zlabel('Stock C')

plt.show()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

A=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])
B=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])
C=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])

Stocks=[A,B,C]

for i in range(len(Stocks)):
  for j in range(len(Stocks[i])):
    Stocks[i][j]=Stocks[i][j]+np.random.normal(0,0.075,1)

ax.scatter(Stocks[0], Stocks[1], Stocks[2], marker='o')

ax.set_xlabel('Stock A')
ax.set_ylabel('Stock B')
ax.set_zlabel('Stock C')

plt.show()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

A=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])
B=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])
C=np.array([0,0.1,0.2,0.25,0.3,0.4,0.4,0.5,0.6,0.6,0.7,1.0])

Stocks=[A,B,C]

for i in range(len(Stocks)):
  for j in range(len(Stocks[i])):
    Stocks[i][j]=Stocks[i][j]+np.random.normal(0,0.125,1)

ax.scatter(Stocks[0], Stocks[1], Stocks[2], marker='o')

ax.set_xlabel('Stock A')
ax.set_ylabel('Stock B')
ax.set_zlabel('Stock C')

plt.show()

