# -*- coding: utf-8 -*-
"""DJIA HAR and HARX graphs (new).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yKTjmWQijRXCfb2gGi-6U1rK9t17rRAv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_excel("Forecasts new.xlsx",index_col='Date')

plt.plot(df.index, df["Actuals"])
plt.plot(df.index, df["HAR"])
plt.ylabel("DJIA Realized Volatility")
plt.xticks(rotation=50)
plt.show()

plt.plot(df.index, df["Actuals"])
plt.plot(df.index, df["HARX"])
plt.ylabel("DJIA Realized Volatility")
plt.xticks(rotation=50)
plt.show()

plt.plot(df.index, df["Actuals"])
plt.plot(df.index, df["HARST - PH"])
plt.ylabel("DJIA Realized Volatility")
plt.xticks(rotation=50)
plt.show()

plt.plot(df.index, df["Actuals"])
plt.plot(df.index, df["HARST (week)"])
plt.ylabel("DJIA Realized Volatility")
plt.xticks(rotation=50)
plt.show()

